int broj=0;
void setup ()
{
pinMode(0, OUTPUT);
pinMode(1, OUTPUT);
pinMode(2, OUTPUT);
pinMode(3, OUTPUT);
pinMode(4, OUTPUT);
pinMode(5, OUTPUT);
pinMode(6, OUTPUT);
pinMode(7, OUTPUT);
pinMode(8, OUTPUT);
pinMode(9, OUTPUT);
pinMode(10, OUTPUT);
pinMode(11, OUTPUT);
pinMode(12, OUTPUT);
pinMode(13, OUTPUT);

}
void loop ()
{
 
switch (broj)
{
case 0:

digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, LOW); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, HIGH);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, LOW); 
digitalWrite ( 12, LOW); 
digitalWrite ( 13, HIGH);  
break;
case 1:

digitalWrite ( 0, HIGH);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, HIGH); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, HIGH); 
digitalWrite ( 6, HIGH);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, LOW); 
digitalWrite ( 12, LOW); 
digitalWrite ( 13, HIGH); 
break;
case 2:

digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, HIGH); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, LOW); 
digitalWrite ( 5, HIGH); 
digitalWrite ( 6, LOW);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, LOW); 
digitalWrite ( 12, LOW); 
digitalWrite ( 13, HIGH); 
break;
case 3:

digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, HIGH); 
digitalWrite ( 6, LOW);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, LOW); 
digitalWrite ( 12, LOW); 
digitalWrite ( 13, HIGH); 
break;
case 4:

digitalWrite ( 0, HIGH);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, HIGH); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, LOW);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, LOW); 
digitalWrite ( 12, LOW); 
digitalWrite ( 13, HIGH); 
break;
case 5:

digitalWrite ( 0, LOW);  
digitalWrite ( 1, HIGH); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, LOW);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, LOW); 
digitalWrite ( 12, LOW); 
digitalWrite ( 13, HIGH); 
break;
case 6:

digitalWrite ( 0, LOW);  
digitalWrite ( 1, HIGH); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, LOW); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, LOW);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, LOW); 
digitalWrite ( 12, LOW); 
digitalWrite ( 13, HIGH); 
break;
case 7:

digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, HIGH); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, HIGH); 
digitalWrite ( 6, HIGH);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, LOW); 
digitalWrite ( 12, LOW); 
digitalWrite ( 13, HIGH); 
break;
case 8:

digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, LOW); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, LOW);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, LOW); 
digitalWrite ( 12, LOW); 
digitalWrite ( 13, HIGH); 
break;

case 9:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, LOW); 
digitalWrite ( 7, LOW);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, LOW); 
digitalWrite ( 12, LOW); 
digitalWrite ( 13, HIGH); 
break;

case 10:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, LOW); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, HIGH);  
digitalWrite ( 7, HIGH);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, HIGH); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, HIGH); 
digitalWrite ( 13, HIGH); 
break;
case 11:
digitalWrite ( 0, HIGH);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, HIGH); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, HIGH); 
digitalWrite ( 6, HIGH);  
digitalWrite ( 7, HIGH);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, HIGH); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, HIGH); 
digitalWrite ( 13, HIGH); 
 break;
case 12:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, HIGH); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, LOW); 
digitalWrite ( 5, HIGH); 
digitalWrite ( 6, LOW);  
digitalWrite ( 7, HIGH);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, HIGH); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, HIGH); 
digitalWrite ( 13, HIGH); 
break;
case 13:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, HIGH); 
digitalWrite ( 6, LOW);  
digitalWrite ( 7, HIGH);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, HIGH); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, HIGH); 
digitalWrite ( 13, HIGH); 

break;
case 14:
digitalWrite ( 0, HIGH);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, HIGH); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, LOW);  
digitalWrite ( 7, HIGH);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, HIGH); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, HIGH); 
digitalWrite ( 13, HIGH); 
break;
case 15:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, HIGH); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, LOW);  
digitalWrite ( 7, HIGH);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, HIGH); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, HIGH); 
digitalWrite ( 13, HIGH); 
break;
case 16:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, HIGH); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, LOW); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, LOW);  
digitalWrite ( 7, HIGH);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, HIGH); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, HIGH); 
digitalWrite ( 13, HIGH); 
break;
case 17:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, HIGH); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, HIGH); 
digitalWrite ( 6, HIGH);  
digitalWrite ( 7, HIGH);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, HIGH); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, HIGH); 
digitalWrite ( 13, HIGH); 
break;
case 18:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, LOW); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, LOW);  
digitalWrite ( 7, HIGH);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, HIGH); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, HIGH); 
digitalWrite ( 13, HIGH); 
break;
case 19:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, LOW); 
digitalWrite ( 7, HIGH);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, HIGH); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, HIGH); 
digitalWrite ( 13, HIGH); 
break;
case 20:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, LOW); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, HIGH);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, HIGH); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, LOW); 
digitalWrite ( 12, HIGH); 
digitalWrite ( 13, LOW);  
break;
case 21:
digitalWrite ( 0, HIGH);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, HIGH); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, HIGH); 
digitalWrite ( 6, HIGH);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, HIGH); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, LOW); 
digitalWrite ( 12, HIGH); 
digitalWrite ( 13, LOW);  
break;
case 22:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, HIGH); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, LOW); 
digitalWrite ( 5, HIGH); 
digitalWrite ( 6, LOW); 
digitalWrite ( 7, LOW);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, HIGH); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, LOW); 
digitalWrite ( 12, HIGH); 
digitalWrite ( 13, LOW);  
break;
case 23:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, HIGH); 
digitalWrite ( 6, LOW);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, HIGH); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, LOW); 
digitalWrite ( 12, HIGH); 
digitalWrite ( 13, LOW);  
break;
case 24:
digitalWrite ( 0, HIGH);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, HIGH); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, LOW);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, HIGH); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, LOW); 
digitalWrite ( 12, HIGH); 
digitalWrite ( 13, LOW);  
break;
case 25:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, HIGH); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, LOW);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, HIGH); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, LOW); 
digitalWrite ( 12, HIGH); 
digitalWrite ( 13, LOW);  
break;
case 26:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, HIGH); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, LOW); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, LOW);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, HIGH); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, LOW); 
digitalWrite ( 12, HIGH); 
digitalWrite ( 13, LOW);  
break;
case 27:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, HIGH); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, HIGH); 
digitalWrite ( 6, HIGH);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, HIGH); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, LOW); 
digitalWrite ( 12, HIGH); 
digitalWrite ( 13, LOW);  
break;
case 28:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, LOW); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, LOW);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, HIGH); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, LOW); 
digitalWrite ( 12, HIGH); 
digitalWrite ( 13, LOW);  
break;
case 29:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, LOW); 
digitalWrite ( 7, LOW);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, HIGH); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, LOW); 
digitalWrite ( 12, HIGH); 
digitalWrite ( 13, LOW);  
break;
case 30:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, LOW); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, HIGH);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, HIGH); 
digitalWrite ( 13, LOW);  
break;
case 31:
digitalWrite ( 0, HIGH);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, HIGH); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, HIGH); 
digitalWrite ( 6, HIGH);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, HIGH); 
digitalWrite ( 13, LOW);  
break;
case 32:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, HIGH); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, LOW); 
digitalWrite ( 5, HIGH); 
digitalWrite ( 6, LOW);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, HIGH); 
digitalWrite ( 13, LOW);  
break;
case 33:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, HIGH); 
digitalWrite ( 6, LOW);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, HIGH); 
digitalWrite ( 13, LOW);  
break;
case 34:
digitalWrite ( 0, HIGH);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, HIGH); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, LOW);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, HIGH); 
digitalWrite ( 13, LOW);  
break;
case 35:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, HIGH); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, LOW);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, HIGH); 
digitalWrite ( 13, LOW);  
break;
case 36:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, HIGH); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, LOW); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, LOW);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, HIGH); 
digitalWrite ( 13, LOW);  
break;
case 37:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, HIGH); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, HIGH); 
digitalWrite ( 6, HIGH);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, HIGH); 
digitalWrite ( 13, LOW);  
break;
case 38:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, LOW); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, LOW);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, HIGH); 
digitalWrite ( 13, LOW);  
break;
case 39:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, LOW); 
digitalWrite ( 7, LOW);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, HIGH); 
digitalWrite ( 13, LOW);  
break;
case 40:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, LOW); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, HIGH);  
digitalWrite ( 7, HIGH);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, HIGH); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, LOW); 
digitalWrite ( 13, LOW);  
break;
case 41:
digitalWrite ( 0, HIGH);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, HIGH); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, HIGH); 
digitalWrite ( 6, HIGH);  
digitalWrite ( 7, HIGH);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, HIGH); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, LOW); 
digitalWrite ( 13, LOW);  
break;
case 42:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, HIGH); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, LOW); 
digitalWrite ( 5, HIGH); 
digitalWrite ( 6, LOW);
digitalWrite ( 7, HIGH);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, HIGH); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, LOW); 
digitalWrite ( 13, LOW);  
break;  
case 43:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, HIGH); 
digitalWrite ( 6, LOW); 
 digitalWrite ( 7, HIGH);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, HIGH); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, LOW); 
digitalWrite ( 13, LOW);  
break;
case 44:
digitalWrite ( 0, HIGH);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, HIGH); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, LOW);  
digitalWrite ( 7, HIGH);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, HIGH); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, LOW); 
digitalWrite ( 13, LOW);  
break;
case 45:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, HIGH); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, LOW);  
digitalWrite ( 7, HIGH);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, HIGH); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, LOW); 
digitalWrite ( 13, LOW);  
break;
case 46:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, HIGH); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, LOW); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, LOW);  
digitalWrite ( 7, HIGH);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, HIGH); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, LOW); 
digitalWrite ( 13, LOW);  
break;
case 47:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, HIGH); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, HIGH); 
digitalWrite ( 6, HIGH);  
digitalWrite ( 7, HIGH);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, HIGH); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, LOW); 
digitalWrite ( 13, LOW);  
break;
case 48:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, LOW); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, LOW);  
digitalWrite ( 7, HIGH);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, HIGH); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, LOW); 
digitalWrite ( 13, LOW);  
break;
case 49:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, LOW); 
digitalWrite ( 7, HIGH);  
digitalWrite ( 8, LOW); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, HIGH); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, LOW); 
digitalWrite ( 13, LOW);  
break;
case 50:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, LOW); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, HIGH);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, HIGH); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, LOW); 
digitalWrite ( 13, LOW);  
break;
case 51:
digitalWrite ( 0, HIGH);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, HIGH); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, HIGH); 
digitalWrite ( 6, HIGH);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, HIGH); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, LOW); 
digitalWrite ( 13, LOW);  
break;
case 52:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, HIGH); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, LOW); 
digitalWrite ( 5, HIGH); 
digitalWrite ( 6, LOW);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, HIGH); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, LOW); 
digitalWrite ( 13, LOW);  
break;
case 53:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, HIGH); 
digitalWrite ( 6, LOW);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, HIGH); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, LOW); 
digitalWrite ( 13, LOW);  
break;
case 54:
digitalWrite ( 0, HIGH);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, HIGH); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, LOW);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, HIGH); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, LOW); 
digitalWrite ( 13, LOW);  
break;
case 55:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, HIGH); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, LOW);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, HIGH); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, LOW); 
digitalWrite ( 13, LOW);  
break;
case 56:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, HIGH); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, LOW); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, LOW);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, HIGH); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, LOW); 
digitalWrite ( 13, LOW);  
break;
case 57:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, HIGH); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, HIGH); 
digitalWrite ( 6, HIGH);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, HIGH); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, LOW); 
digitalWrite ( 13, LOW);  
break;
case 58:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, LOW); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, LOW);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, HIGH); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, LOW); 
digitalWrite ( 13, LOW);  
break;
case 59:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, HIGH); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, LOW); 
digitalWrite ( 7, LOW);  
digitalWrite ( 8, HIGH); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, HIGH); 
digitalWrite ( 12, LOW); 
digitalWrite ( 13, LOW);  
break;
case 60:
digitalWrite ( 0, LOW);  
digitalWrite ( 1, LOW); 
digitalWrite ( 2, LOW); 
digitalWrite ( 3, LOW); 
digitalWrite ( 4, LOW); 
digitalWrite ( 5, LOW); 
digitalWrite ( 6, HIGH);  
digitalWrite ( 7, LOW);  
digitalWrite ( 8, HIGH); 
digitalWrite ( 9, LOW); 
digitalWrite ( 10, LOW); 
digitalWrite ( 11, LOW); 
digitalWrite ( 12, LOW); 
digitalWrite ( 13, LOW);  
break;
case 61:
broj=-1;
break;
}
delay (1000);
broj=broj+1;

}
